language: generic
# tells travis we need super user permissions
sudo: required

# tells travis  we need a copy of docker
services:
  - docker

# commands executed before our tests are ran
before_install:
  - docker build -t lucasgmm20/docker-react -f Dockerfile.dev .

# commands executed to run the test suite
script:
  - docker run -e CI=true lucasgmm20/docker-react npm run test
