language: generic
sudo: required # tells travis we need super user permissions
services: # tells travis we need a copy of docker
  - docker
before_install: # commands executed before our tests are ran
  - docker build -t lucasgmm20/docker-react -f Dockerfile.dev .
script: # commands executed to run the test suite
  - docker run -e CI=true lucasgmm20/docker-react npm run test
